bmax121/APatch

apd/src/apd.rs
app/src/main/java/me/bmax/apatch/APatchApp.kt
app/src/main/java/me/bmax/apatch/ui/screen/Settings.kt
app/src/main/java/me/bmax/apatch/util/APatchCli.kt
app/src/main/res/values/strings.xml

This pull request introduces a setting to enforce the global mount namespace for root sessions. 
This is achieved by reading an hidden file called `global_namespace_enable` that will be placed in `/data/adb/`. 
Some apps, such as [Solid Explorer](https://play.google.com/store/apps/details?id=pl.solidexplorer2), do not function properly with the default namespace, and forcing the global mount resolves the issue.
| ![before](https://github.com/bmax121/APatch/assets/8174240/20154508-2e89-4a22-a86c-dc49b8ba60d7) | ![after](https://github.com/bmax121/APatch/assets/8174240/f92133d3-d6f9-438b-8998-c36260ca3ce4) |
| --- | --- |
| Toggle OFF | Toggle ON |
I don't know if having all root sessions use the global namespace can cause any issues somewhere; with Magisk, I've always kept it that way and …

Added a setting to force global mount namespace

---

app/src/main/java/me/bmax/apatch/util/APatchCli.kt

Some users (as reported in issue #134) are experiencing an issue with the **Global Namespace Mode** setting not remaining active after closing and reopening the settings. 
This problem is due to the fact that the command `cat /data/adb/.global_namespace_enable` returns nothing and exits with _error code 1_, even though the file is present.
Actually, the issue seems to affect all options that execute commands with the root shell, such as the reboot command. 
After some time, the problem started appearing on my phone as well, but after making some changes, it seems to have been resolved. 
Let's try to merge it and see if the issue is also resolved for other users.

[Fix] global namespace mode setting

---

app/src/main/res/values/arrays.xml

The names of "粤语（简体）" and "粤语（繁体）" in the current language picker are not expressed appropriately. The original term "粤语" refers only to one dialect among Simplified Chinese. The correct expressions should be "简体中文"  and "繁体中文". Hoping that you can merge my commit, making APatch better.

Change the Chinese language names in the language picker to the most suitable character for Chinese expression habits

---

app/src/main/assets/boot_patch.sh
app/src/main/assets/util_functions.sh
app/src/main/java/me/bmax/apatch/APatchApp.kt
app/src/main/java/me/bmax/apatch/Natives.kt
app/src/main/java/me/bmax/apatch/ui/screen/Home.kt
app/src/main/java/me/bmax/apatch/ui/screen/Patch.kt
app/src/main/java/me/bmax/apatch/util/APatchCli.kt
app/src/main/java/me/bmax/apatch/util/LogEvent.kt
app/src/main/res/values/strings.xml

Description:
- Add an update function of `KernelPatch` for direct installation when an update of `kpatch` is available
- Add an update button to the `KernelPatch`
- Update the `KernelPatch` card to have less information (more room for the new update button)
- Add superuser and module count information to the `KernelPatch` card similar to what `KernelSU` has
- This is just to prevent having only the version information on this card, we can think of another (small) useful info to have here
- Add an Info dialog to keep the information of the `su` and `kpatch` paths that were previously in the card itself
- This dialog can be opened by a click on the `KernelPatch` card
- Multiple small improvements ad typo fixes on the code overall
Demo (version file was changed manually to simulate a new …

feat: update kernel on kpatch update and update Home screen

---

apd/src/installer.sh

Updated the Magisk version to 27.0 and the Magisk Version Code to 27000 (latest beta).
Latest canary/debug would be 27001.
Edit: Magisk stable got pushed to 27.0 too.

magisk: 26.4.4 -> 27.0

---

apd/Cargo.toml
apd/src/defs.rs
apd/src/event.rs
apd/src/mount.rs
apd/src/utils.rs

temp_mount

---

app/src/main/java/me/bmax/apatch/ui/screen/Patches.kt

PatchViewModel's embed kpm author and license strings were reversed.
Before the patch:
author:GPL v2
license:xxx
After:
author:xxx
license:GPL v2
Test: build, patch, embed new kpm, author and license were corrected.

manager: Correct reversed author and license strings

---

.github/dependabot.yml

It's a mistake made by me. ;)
Our branch's name is 'main'.

dependabot: Trigger on main branch

---

app/src/main/java/me/bmax/apatch/ui/screen/Home.kt

During my tests, setting keyboardType to KeyboardType.Password made it
unable to enter superkey. Maybe it was something wrong in latest deps.
Instead of finding a better solution, temporarily removing keyboardType
is a good idea until we fix it.

manager: Fix unable to enter superkey

---

app/src/main/java/me/bmax/apatch/APatchApp.kt

As long as KPATCH_PATH is still in use, the latest version should be extracted.

manager: Always extract kpatch

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/me/bmax/apatch/ui/screen/Settings.kt
app/src/main/java/me/bmax/apatch/util/AXML.kt
app/src/main/java/me/bmax/apatch/util/HideAPK.kt
app/src/main/java/me/bmax/apatch/util/Keygen.kt
app/src/main/java/me/bmax/apatch/util/apksign/ApkSignerV2.java
app/src/main/java/me/bmax/apatch/util/apksign/ByteArrayStream.java
app/src/main/java/me/bmax/apatch/util/apksign/JarMap.java
app/src/main/java/me/bmax/apatch/util/apksign/SignApk.java
app/src/main/java/me/bmax/apatch/util/apksign/ZipUtils.java
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

[feature] manager: Introduce Hide APatch Manager
Since apps can detect APatch via its manager's packageName, whether it has the permission
to read app list or not, exposing original manager packageName is dangerous. Here is a
simple method to generate a new random packageName and customized name manager to bypass
the check.
#222 also required this feature.
Credit: topjohwnu's Magisk about apksign's codes and some good ideas.

manager: Introduce Hide APatch Manager feature

---

app/src/main/java/me/bmax/apatch/ui/screen/SuperUser.kt

The functionality to exclude modules has not been implemented yet. The current presence of the button may cause confusion for some users, so it should be hidden for now and made visible again once the feature is implemented.

Hide exclude module button, Actually it doesn't work now,

---

app/src/main/assets/util_functions.sh

- Replace direct image writing with `dd` command utilizing block size parameter for optimized block device operations.
- Ensure complete block reads and data integrity by incorporating `iflag=fullblock` and `conv=notrunc,fsync` options in `dd`.
- Eliminate the previous method of zero-padding to prevent potential incomplete flashing.
- Execute `sync` post-write to guarantee all data is properly flushed to the device.
- Provide detailed user feedback for non-block or char device scenarios, enhancing clarity.
Fixes: https://github.com/bmax121/APatch/pull/247#issuecomment-1980231945

Refine flash_image function for enhanced Image flashing operations

---

app/src/main/java/me/bmax/apatch/ui/screen/KPM.kt

Original string: "No support now!"
Proposed string: "Not supported yet!"
The phrase "not supported yet" is used it to indicate that a certain item, service, feature, or option is not yet available. For example, "This feature is not supported yet but it should be available soon.".

Correct grammar

---

README.md
app/src/main/java/me/bmax/apatch/ui/screen/Home.kt

昨天APatch的官方文档地址从<https://apatch.top>换成了<https://apatch.dev>[1]，故修改README和App本体内的文档指向域名
[1] https://github.com/AndroidPatch/APatchDocs/commit/fe111016dda2b64f06f93af6caf34f6d132a455a

manager, README: Correct the domain for document

---

app/build.gradle.kts
scripts/InstallAP.sh
scripts/UninstallAP.sh
scripts/update_binary.sh
scripts/update_script.sh

Add flash script into APatch Manager, with that, users can more easier to get APatch like how they get Magisk.
It's default key is apatch66
We have reverted some codes which have removed in https://github.com/bmax121/APatch/commit/8c5c34e35d9836aa8aaebff6bcab9b3588868ea2, without them, we can't include flash script into Manager.
We have deleted outdated flash script in assest folder(https://github.com/bmax121/APatch/commit/7e81c81d9dd417354d124eff22a25c42265e1c44), we don't need it for now.
Test: Build Manager - Flash in Third-Party Recovery - Reboot - Enter default key - Check APatch
Result: It works well(Tested on Oneplus Ace 3 Pro)
Needs to improve:
- Need to add Kernel Flags detecte

manager: Add flash script into APatch Manager

---

scripts/extract-ikconfig

With tests, mktemp won't provided in some Recovery then it will abort because of the incorrect kernel configuration detection result. We have use mktemp provided by toybox to avoid this issue.
Test: Build Manager - Flash in Recovery - Check result
Result: It can work on some recovery which not provide mktemp

scripts: kernel configuration detection script bug fix

---

app/src/main/assets/boot_patch.sh
app/src/main/assets/extract-ikconfig

In commit https://github.com/bmax121/APatch/commit/6d62eaebcf6fdfa08253da2386d2b17557bbce24, we used mktemp provided by toybox to avoid the problem of missing mktemp. However, the test found that permission denied would occur on some devices because mktemp provided by toybox would create temporary files in /tmp, which is not possible in non-Recovery. Therefore, we added the parameter of passing in the APP cache directory to the APP patch script as the directory for mktemp to generate temporary files. This parameter is not passed in when flashing in Recovery mode.
Test: Build Manager - Patch in the device that not have mktemp - Check result
Result: It's working fine now(Tested on Redmi Note 11 5G)

scripts: Fixed detecting kernel configuration in APP

---

app/src/main/assets/InstallAP.sh
app/src/main/assets/boot_patch.sh
app/src/main/assets/extract-ikconfig

In previous commits https://github.com/bmax121/APatch/commit/6d62eaebcf6fdfa08253da2386d2b17557bbce24 and https://github.com/bmax121/APatch/commit/38649e07e156ff00b8b396f781b284db20300134, we tried to fix the kernel configuration detection error when patching kernel via app or flashing in recovery, but after a lot of testing, we still found that it does not work properly in some extreme cases, such as when the user changes the APP package name.
In response to this, this commit updates the extract-ikconfig script to use a newer implementation to detect kernel configuration and does not use the mktemp command, which means that the problem of mktemp not existing in some systems and recovery will no longer occur. At the same time, since there is no need to use mktemp to create temporary …

scripts: Completely fix kernel configuration detection

---

app/src/main/java/me/bmax/apatch/ui/screen/Patches.kt
app/src/main/java/me/bmax/apatch/ui/viewmodel/PatchesViewModel.kt
app/src/main/res/values/strings.xml

When patching in APP, users usually use special characters as SuperKey for security reasons. However, since users often use special characters that may cause program errors as SuperKey, special character detection is added.
While ensuring that most special characters can still be used as SuperKey normally, the special character detection added this time only includes $ " ' [ ], which are special symbols that are easy to cause program errors. Other special symbols such as @ # are not affected.
Test: Build Manager - Patch kernel with using special character that not allow - Patch won't start and throw error note

Manager: Add SuperKey special character detection

---

app/src/main/assets/boot_patch.sh
app/src/main/java/me/bmax/apatch/ui/screen/Patches.kt
app/src/main/java/me/bmax/apatch/ui/viewmodel/PatchesViewModel.kt
app/src/main/res/values/strings.xml

In commit https://github.com/bmax121/APatch/commit/93154859b69e588f413adff397a80e7c45598987, we did not allow some special characters to be set as SuperKey because they would cause the program error. Now I have fixed the issue that using special characters as SuperKey would cause program errors, so I have also reverted that commit.
Before this PR, the manager won't use array concatenation when running patch scripts. Some special characters, such as $ " ' [ ] `, would cause unexpected behavior, resulting in runtime errors. But now we use array concatenation when running patch scripts, so it will not cause errors. Users can use all special characters as SuperKey, which improves security.
Test: Build manager - patch kernel with special characters - now works fine

Support all special characters as super key

---

app/src/main/assets/boot_patch.sh

After patching is complete, check if the kernel configuration CONFIG_KALLSYMS_ALL is set, otherwise warn the user that kernel configuration is not set and bootloop may occur.

script: Add kernel configuration CONFIG_KALLSYMS_ALL detection

---

apd/src/assets.rs
app/src/main/java/me/bmax/apatch/APatchApp.kt

Some modules expect magiskboot to be available in PATH. Add binary to ap/bin folder so it is available in PATH

Add magiskboot to bin folder

---

app/src/main/java/me/bmax/apatch/ui/screen/SuperUser.kt

https://github.com/user-attachments/assets/66c88f52-fb5f-4d68-a41e-8aa3bfc4db3d

manager: Use `AnimatedVisibility` for Exclude Modifications `SwitchItem`

---

apd/src/mount.rs

A shared mount point will create a new mounting peer group. It results in a new detection point, because after unmounting these mount points, gaps will appear in peer group IDs. One can check these gaps by the command
```
cat /proc/self/mountinfo | grep -Eo "master:.." | cut -d':' -f2 | sort | uniq
```
In Holmes V1.5.1, the above detection point is named as Evil Modification (04).

Mount tmpfs as private

---

README.md

This commit will modify the README.md file in order to correct a wrong description about kernel hook function inline-hook and syscall-table-hook which firstly appeared at documentation in AndroidPatch/APatchDocs caused by non-fully understanding about these hook functions.

upd: README.md

---

app/src/main/java/me/bmax/apatch/APatchApp.kt
app/src/main/java/me/bmax/apatch/Natives.kt
app/src/main/java/me/bmax/apatch/util/PkgConfig.kt

In the CONFIG_FILE, there is a field for selinux context label. Though this field is not wildely used by APatch or Android modules, it is confusing to have its default always to be `magisk`.
For example, if one sets an app to be excluded, then in the file `/data/adb/ap/package_config`, its selinux context is shown to be `u:r:magisk:s0`, which is not reasonable. It is better to use the Android default context for applications to avoid confusions (of module developers who parse this file).

Show default selinux context as untrusted_app

---

app/src/main/java/me/bmax/apatch/util/Downloader.kt
app/src/main/res/values-az/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ms/strings.xml
app/src/main/res/values-nb-rNO/strings.xml

pixel 4xl lineageOS22 安卓15 和 redmi pad 安卓15 使用 apatch 11039 都无法root
自行使用 KernelPatch 0.12.0 都可以成功root 但是apatch 显示让我反向更新
发现 apatch main 分支提供了 已经提交了 KernelPatch 0.12.0 支持 于是想自行编译下
一直打包不成功,原来是android studio 版本太低的问题. 升级 android studio 解决了.这代码提交不提交无所谓了.
低版本 android studio 打包时修改的代码
registerReceiver 修改的更优雅
string.xml 中 apatch_version 有的是 Version: %s 有的是 Versi: %d.%d.%d
可能是个别语言 编码问题,我认为阿拉伯数字的字符串应该是通用的
我统一改成了 %s
不知道改的对不对
另外不知道为什么 我发布 签名发布 release 版本全部闪退
不签名 debug 版本就没问题

app: Fix fmt string mismatch and use `ContextCompat`
