- README.md
- app/src/main/java/me/bmax/apatch/ui/screen/APM.kt
- app/src/main/java/me/bmax/apatch/ui/screen/Home.kt
- app/src/main/res/values/strings.xml
Moved "Android Patch Not Installed" and "Clear Key" strings to strings.xml
> Fixed FAQ link in README.md and refactored two strings to strings.xml

- app/src/main/java/me/bmax/apatch/ui/screen/APM.kt
- app/src/main/java/me/bmax/apatch/ui/screen/KPM.kt
- app/src/main/java/me/bmax/apatch/util/Extensions.kt
Added animation to the FABs in the APKModule and KPModule sections when scrolling the list
> [Enhancement] Added animation to the FABs

- docs/cn/faq_cn.md
Update Chinese FAQ to the latest.
> Update Chinese(Simplified) FAQ

- app/src/main/java/me/bmax/apatch/ui/screen/Home.kt
- app/src/main/res/values/strings.xml
Moved "Patch" string to strings.xml so it can be translated.
Fix for issue #114.
> Refactored string to strings.xml

- apd/Cargo.toml
- apd/src/defs.rs
- apd/src/event.rs
- apd/src/mount.rs
> Upgrade apd mount

- .github/workflows/apd.yml
- .github/workflows/build.yml
- app/build.gradle.kts
- build.gradle.kts
> Revert "build: add apd build to gradle workflow and publish only on tag push"

- app/src/main/java/me/bmax/apatch/ui/screen/Settings.kt
- app/src/main/java/me/bmax/apatch/util/APatchCli.kt
- app/src/main/java/me/bmax/apatch/util/HideAPK.kt
APatch has no root permission by default, so use libkpatch.so to su
> fix: install hiding apk failed

- apd/src/cli.rs
This reverts commit 81fd11c98bc0bb90d6d787945f9e54edc94408cc.
> Revert "compat: termux's su (#262)"

- app/src/main/assets/boot_extract ota.sh
- app/src/main/assets/util_functions.sh
- app/src/main/java/me/bmax/apatch/ui/viewmodel/PatchesViewModel.kt
> fix A olny devices update

- docs/de/faq_de.md
Updated the german translation of the FAQ (frequently asked questions).
Removed the part that got removed in the original (english) version too.
> faq: Updated german translation

- app/src/main/java/me/bmax/apatch/ui/screen/Home.kt
> AuthSuperKey: Restore keyboardType = KeyboardType.Password

- apd/src/mount.rs
add more infomation when mount
> apd: add more infomation when mount

- scripts/update_binary.sh
> Fix print job

- scripts/update_binary.sh
- scripts/update_script.sh
As I am a native english speaker, I have fixed some questionable english in these scripts.
> Fix some english

- apd/Cargo.lock
- apd/Cargo.toml
- apd/src/apd.rs
- apd/src/cli.rs
- apd/src/event.rs
- apd/src/package.rs
- apd/src/supercall.rs
- app/src/main/cpp/version
- build.gradle.kts
> apd: Add `uid-monitor` to sync uid from system

- app/build.gradle.kts
- app/src/main/assets/boot_patch.sh
- app/src/main/java/me/bmax/apatch/ui/viewmodel/PatchesViewModel.kt
- scripts/InstallAP.sh
- scripts/UninstallAP.sh
- scripts/extract-ikconfig
- scripts/update_binary.sh
- scripts/update_script.sh
> Add AOSP recovery support & Detect kernel configuration & Various bug fixes

- app/src/main/java/me/bmax/apatch/ui/viewmodel/PatchesViewModel.kt
While refactoring installationcode in https://github.com/bmax121/APatch/commit/521a5bd590b7899014444532436fd77122d574ed, overlooked the `su` method used in older KernelPatch versions(0.10.7 and lower)
> Manager: Fixed issue when upgrading KernelPatch

- app/src/main/java/me/bmax/apatch/ui/MainActivity.kt
- app/src/main/java/me/bmax/apatch/ui/screen/Settings.kt
- app/src/main/res/values/themes.xml
> manager: Fix save log

- app/src/main/java/me/bmax/apatch/ui/screen/ExecuteAPMAction.kt
要不要 delay idk
我不太清楚是不是所有模块都在执行结束后 sleep 了
决定好再合）
> manager: Add `popBackStack()` for ExecuteAPMActionScreen when action finished

- app/src/main/AndroidManifest.xml
- app/src/main/java/me/bmax/apatch/APatchApp.kt
- app/src/main/java/me/bmax/apatch/ui/CrashHandleActivity.kt
- app/src/main/java/me/bmax/apatch/ui/MainActivity.kt
- app/src/main/java/me/bmax/apatch/ui/screen/Settings.kt
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
https://github.com/user-attachments/assets/9a6a485b-ed55-498d-858c-61ba720cbbde
> manager: Opt save log, Introduce CrashHandleActivity

- app/src/main/res/values/strings.xml
Further defined Super Key requirements (tested on sunfish) 
Extended "Authentication failed" reasons
> app: define Super Key requirements

- app/src/main/res/values/strings.xml
An enhanced English translation aimed at achieving greater fluency, grammatical accuracy, and natural readability.
> Update English translation

- app/src/main/assets/InstallAP.sh
New apatch versions require letters in the password.
> Fix random key with only numbers and no letters

- apd/src/package.rs
- gradle/wrapper/gradle-wrapper.properties
> apd: fix unauthorized apps in package_config
